version: '3.1'
services:
  web:
    image: jupyter_mega-rcd
    restart: unless-stopped
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      NB_USER: "suporte"
      CHOWN_HOME: "yes"
    ports:
      - 8080:8888
    volumes:
      - /home/suporte/Jupyter:/home/suporte/Projeto